version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: health_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: health_fastapi_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/health_db
      - JWT_SECRET_KEY=PHI_HEALTH_APP_SECRET_JWT_TOKEN_KEY_2026
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: health_react_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
